//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   There are no key-value pairs in the ResourceList parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyResourceList {
            get {
                return ResourceManager.GetString("EmptyResourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file &apos;{0}&apos; already exists. It able to be overwritten with the Force parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generating file &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneratingFile {
            get {
                return ResourceManager.GetString("GeneratingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no valid key-value pairs in the file &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFormatFile {
            get {
                return ResourceManager.GetString("InvalidFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The line read &apos;{0}&apos; is not a key-value pair. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidKeyValuePair {
            get {
                return ResourceManager.GetString("InvalidKeyValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current provider &apos;{0}&apos; is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFileSystemProvider {
            get {
                return ResourceManager.GetString("NotFileSystemProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find path &apos;{0}&apos; because it does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
    }
}
